main == preset-uncommon
cybercoder-naj/logestic pull request #28
Opened 2024-05-25 18:20 UTC by suryavirkapur

![image](https://github.com/cybercoder-naj/logestic/assets/52126281/4fb2e787-d6eb-492c-b104-db14638be1b0)

### Uncommon
- Use Data `.toString()` so I can get the time according to my current TZ.

2024-05-26 12:33 UTC, cybercoder-naj commented
Thanks for the PR; I will look into this soon.

2024-05-26 19:35 UTC, cybercoder-naj requested changes
Additionally, it'll be great to have a screenshot image inside `screenshots/` folder so I put it in the wiki.

2024-05-26 19:35 UTC, cybercoder-naj commented on src/presets/index.ts
> +import uncommon from './common';
I think you have a typo here, it should import from `./uncommon`

2024-05-26 19:35 UTC, cybercoder-naj commented on src/presets/uncommon.ts
I think `uncommon` is a confusing name for this preset. Can you think of something else?

2024-05-27 11:18 UTC, suryavirkapur commented on src/presets/uncommon.ts
I named it `commontz` which suggests it's just the common design with a timezone.

2024-05-27 11:19 UTC, suryavirkapur commented
You can review the changes now. 
- sk

2024-05-27 12:18 UTC, merged